services:
  web:
    image: dockette/web:php-83
    volumes:
      - ./:/srv
    container_name: "nette4"
    ports:
    - ${HTTP_PORT}:80
    - ${HTTPS_PORT}:443
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080